---
name: build_push_on_gcp

env:
  REPO_NAME: ${github.event.repository.name}
  APPNAME: coms-ui #THIS CANNOT CONTAIN ANY MAJ
  TAG: latest
  APP_ENV: dev
  WORKING_DIR: ./front

on:
  push:
    branches:
      - develop

permissions:
  id-token: "write"
  contents: "read"
  repository-projects: "write"
  pull-requests: "write"

jobs:
  build-container:
    runs-on: ubuntu-20.04
    environment:
      name: Test_build

    steps:
      - name: checkout v3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Setup app project dependencies
        working-directory: ${{env.WORKING_DIR}}
        run: npm install

      - name: Set the build version value
        working-directory: ${{env.WORKING_DIR}}
        run: |
          echo "TAG=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Display old Tag Value
        run: |
          echo "${{ env.TAG }}"
      - name: Bump build version value
        working-directory: ${{env.WORKING_DIR}}
        run: |
          npm run bump

      - name: Set the build version value after bump
        working-directory: ${{env.WORKING_DIR}}
        run: |
          echo "TAG=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Display New Tag Value
        run: |
          echo "${{ env.TAG }}"

      - name: Git config
        run: |
          git config --global user.name mohamed.bouaziz
          git config --global user.email mohamed.bouaziz@cision.com

      - name: Git commit and push new build version number
        run: |
          git commit --no-verify -am "[skip ci] auto bump metadata version"
          git push -u origin develop

    outputs:
      newversion: "${{ env.TAG }}"

  checkout-release:
    needs: build-container
    runs-on: ubuntu-20.04
    environment:
      name: Test_build

    steps:
      - name: Checkout release project
        uses: actions/checkout@v3
        with:
          repository: mohamedDev/release
          token: ${{ secrets.BOT_ACCESS_TOKEN }} # `GH_PAT` is a secret that contains your PAT(personal access token)
          ref: testpr

      - name: Display New Tag Value
        run: |
          echo "${{ needs.build-container.outputs.newversion }}"

      - name: Git status
        run: |
          git status
          git config --global user.name mohamed.bouaziz
          git config --global user.email mohamed.bouaziz@cision.com
          ls -al
          sed -i 's/latest/${{ needs.build-container.outputs.newversion }}/g' package.json
          git status
          
          if ! git diff-index --quiet HEAD --; then
            git commit --no-verify -am "[skip ci] replace with new version"
            git push -u origin testpr
          else 
            echo "no changes"
          fi
      - name: Git commit and push
        run: |
          git commit --no-verify -am "[skip ci] auto bump metadata version"
          git push -u origin develop

