---
name: pr

env:
  REPO_NAME: ${github.event.repository.name}
  APPNAME: coms-ui #THIS CANNOT CONTAIN ANY MAJ
  TAG: latest
  APP_ENV: dev
  WORKING_DIR: ./front

on:
  push:
    branches:
      - feature/*

permissions:
  id-token: "write"
  contents: "read"
  repository-projects: "write"
  pull-requests: "write"

jobs:
  build-container:
    runs-on: ubuntu-20.04
    environment:
      name: Test_build

    steps:
      - name: checkout v3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Setup app project dependencies
        working-directory: ${{env.WORKING_DIR}}
        run: npm install

      - name: Bump build version value
        working-directory: ${{env.WORKING_DIR}}
        run: |
          npm run bump

      - name: Set the build version value after bump
        working-directory: ${{env.WORKING_DIR}}
        run: |
          echo "TAG=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Git config
        run: |
          git config --global user.name mohamed.bouaziz
          git config --global user.email mohamed.bouaziz@cision.com

      - name: Git commit and push new build version number
        run: |
          git commit --no-verify -am "[skip ci] auto bump metadata version"
          git push -u origin ${{ github.ref_name }}

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'develop',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
           

