---
name: CD-release_prod

env:
  REPO_NAME: ${{ github.event.repository.name }}
  APPNAME: coms-ui-prod #THIS CANNOT CONTAIN ANY MAJ
  PR: ${{ github.event.pull_request.number }}
  TAG: latest
  PATH_DOCKERFILE: ./front
  APP_ENV: prod
  WORKING_DIR: ./front

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       

      - name: test
        run: |
          git status
          ls -al
          cat front/package.json
          cat front/CHANGELOG.md
