---
name: test pr

env:
  REPO_NAME: ${github.event.repository.name}
  APPNAME: coms-ui #THIS CANNOT CONTAIN ANY MAJ
  TAG: latest
  APP_ENV: dev
  WORKING_DIR: ./front

on:
  push:
    branches: [develop]

permissions:
  id-token: "write"
  contents: "read"
  repository-projects: "write"
  pull-requests: "write"

jobs:
  build-container:
    runs-on: ubuntu-20.04
    environment:
      name: Test_build

    steps:
      - name: checkout v3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            console.log(repo, owner)
            /*const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo: 'release',
              head: '${{ github.ref_name }}',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });*/
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT}}
        run: |
          gh pr create --base main --head develop --title "fix(docker): update docker image version" --body "This PR is auto-generated " --repo release
